services:
  ui:
    build:
      context: .
      dockerfile: Dockerfile.hodrl
      args:
        HODRL_CLIENT: ui
    command: hodrl-ui
    container_name: hODRL-ui
    restart: unless-stopped
    ports:
      - '8050:8050'
    networks:
      - hODRL

  api:
    build:
      context: .
      dockerfile: Dockerfile.hodrl
      args:
        HODRL_CLIENT: api
    command: hodrl-api
    container_name: hODRL-api
    restart: unless-stopped
    ports:
      - '8000:8000'
    networks:
      - hODRL

  cli:
    build:
      context: .
      dockerfile: Dockerfile.hodrl
      args:
        HODRL_CLIENT: cli
    command: hodrl-cli
    container_name: hODRL-cli
    profiles: ["manual"]
    networks:
      - hODRL

  metadata-store:
    image: stain/jena-fuseki
    container_name: hODRL-metadata-store
    restart: unless-stopped
    ports:
      - "3030:3030"
    environment:
      ADMIN_PASSWORD: admin
    volumes:
      - jena-data:/fuseki
      - ./config/metadata-store/config.ttl:/fuseki/config.ttl
      - ./config/metadata-store/vocabulary.ttl:/fuseki/vocabulary.ttl
      - ./hodrl/test/data/ODRL-w3c-examples.ttl:/fuseki/data.ttl # temporary2
    networks:
      - hODRL

networks:
  hODRL:
    name: hODRL

volumes:
  jena-data:
    name: jena-data
  
