services:
  ui:
    build:
      context: .
      dockerfile_inline: |
        FROM python:3.13-slim
        COPY . /hodrl
        RUN pip install ./hodrl[ui]
        CMD ["hodrl-ui"]
    container_name: hODRL-ui
    restart: unless-stopped
    ports:
      - '8050:8050'
    networks:
      - hODRL

  api:
    build:
      context: .
      dockerfile_inline: |        
        FROM python:3.13-slim
        COPY . /hodrl
        RUN pip install ./hodrl[api]
        CMD ["hodrl-api"]
        #CMD ["fastapi", "run", "app/main.py", "--port", "8000", "--workers", "4"]
    container_name: hODRL-api
    restart: unless-stopped
    ports:
      - '8000:8000'
    volumes:
      - ./api/:/app/
    command: uvicorn main:app --host 0.0.0.0 --reload
    networks:
      - hODRL

  metadata-store:
    build:
      context: .
      dockerfile_inline: |
        FROM stain/jena-fuseki
        COPY config/metadata-store/config.ttl /fuseki/config.ttl
        COPY config/metadata-store/vocabulary.ttl /fuseki/vocabulary.ttl
    container_name: hODRL-metadata-store
    restart: unless-stopped
    ports:
      - "3030:3030"
    environment:
      ADMIN_PASSWORD: admin
    volumes:
      - jena-data:/fuseki
    networks:
      - hODRL

networks:
  hODRL:
    name: hODRL

volumes:
  jena-data:
    name: jena-data
  
